package pidev_mobile;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.io.Preferences;
import com.codename1.messaging.Message;
import pidev_mobile.gui.evenement.FormAcceuilEvent;
import pidev_mobile.back.AdminReclamation.ARAccueil;



import pidev_mobile.gui.formation.FormAcceuilFormation;
import pidev_mobile.gui.formation.FormAjoutFormation;
import pidev_mobile.gui.formation.FormMapFormation;

import pidev_mobile.gui.utilisateur.ProfileForm;
import pidev_mobile.gui.utilisateur.WalkthruForm;
import pidev_mobile.back.superAdmin.SAAccueil;
import pidev_mobile.gui.reclamation.AfficherReclamation;
import pidev_mobile.gui.utilisateur.SignInForm;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    public static Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Disable the global toolbar as we want a layered toolbar
        Toolbar.setGlobalToolbar(false);

        // Pro only feature, uncomment if you have a pro subscription
        Log.bindCrashProtection(true);
        
        addNetworkErrorListener(err ->{
            err.consume();
            if(err.getError()!= null){
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error","There was a networking Error"+err.getConnectionRequest().getUrl(),"ok",null);
        });
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        //Preferences.set("type","SuperAdmin");
        //Preferences.set("type","AdminReclamation");
         //new SignInForm(theme).show();
         //new ARAccueil(theme).show();
         //new SAAccueil(theme).show();
       //new Evenement(theme).show();
      // new FormMapFormation(current).show();
      //new FormAcceuilEvent(theme).show();
      Preferences.set("type","freelancer");
               new AfficherReclamation(theme).show();

    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }
}
